name: Apptainer Build Deploy
on:
  pull_request:
  push:
    branches: main
jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: quay.io/singularity/singularity:v4.1.0
      options: --privileged
    name: Build Container
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4
      - name: Build Container
        run: |
          singularity build container.sif Apptainer
      - name: Login and Deploy Container
        run: |
          singularity remote add --no-login ghcr oras://ghcr.io
          echo ${{ github.token }} | singularity remote login --username ${{ github.actor }} --password-stdin ghcr
          TAG=${GITHUB_SHA::7}
          singularity push container.sif ghcr:${GITHUB_REPOSITORY}:${TAG}