name: Apptainer Build Deploy

on:
  pull_request:
  push:
    branches: main

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
      image: quay.io/singularity/singularity:v4.1.0
      options: --privileged

    name: Build and Deploy Container
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Container
        run: |
          singularity build container.sif Apptainer.def

      - name: Install ORAS
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v0.16.0/oras_0.16.0_linux_amd64.tar.gz
          tar -xvf oras_0.16.0_linux_amd64.tar.gz
          mv oras /usr/local/bin/

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push Container to GHCR
        run: |
          oras push ghcr.io/${{ github.repository }}/container.sif:latest container.sif
